schema_version: 1

context:
  python_min: "3.10"
  version: "1.4.0"

package:
  name: e3sm_compareview
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/e3sm_compareview/e3sm_compareview-${{ version }}.tar.gz
  sha256: 5ed517ee828ed06c6b2b698a1412e824d6f8fcf1e369777f044d34077b030588

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - compareview = e3sm_compareview.app:main
      - quickcompare = e3sm_compareview.app:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - numpy <2.4
    - trame >=3.12
    - trame-rca >=2.3.1
    - trame-vuetify >=3.1
    - pyproj >=3.6.1
    - netcdf4 >=1.6.5
    - trame-dataclass >=2.0.2
    - trame-components
    - trame-tauri >=0.6.2
    - pillow
    - e3sm-quickview >=2.5.1

tests:
  - python:
      imports:
        - e3sm_compareview
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - compareview --help
      - quickcompare --help

about:
  summary: An application to explore/analyze data for atmosphere component for E3SM
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/e3sm-compareview/

extra:
  recipe-maintainers:
    - willdunklin
