schema_version: 1

context:
  python_min: "3.11"
  version: "1.10.1"

package:
  name: e3sm_compareview
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/e3sm_compareview/e3sm_compareview-${{ version }}.tar.gz
  sha256: 5dd38cd053895312940f68b0ec0b3522e764fa8c01ef042d71d2ec76cf7207b0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - compareview = e3sm_compareview.app:main
      - quickcompare = e3sm_compareview.app:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - e3sm-quickview >=2.9.3
    - trame-colormaps >=1.6.1
    - numpy <2.4
    - hdf5 <2

tests:
  - python:
      imports:
        - e3sm_compareview
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - compareview --help
      - quickcompare --help

about:
  summary: An application to explore/analyze data for atmosphere component for E3SM
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/e3sm-compareview/

extra:
  recipe-maintainers:
    - jourdain
    - willdunklin
